---
name: brainhask
version: 0.0.0.0

license: MIT
license-file: LICENSE

extra-source-files: brainfucks/*.bf

dependencies:
  - base
  - parsec
  - either
  - transformers
  - pipes
  - bytestring
  - optparse-applicative
  - optparse-generic
  - directory
  - criterion
  - pretty-simple

library:
  source-dirs: ./src/

executables:
  brainhask:
    main: Main.hs
    source-dirs: ./src/
    ghc-options:
      - -O2
      - -funbox-strict-fields
      - -rtsopts
      - -threaded
      - -with-rtsopts=-N
      - -Wall

  brainhask-bench:
    main: Main.hs
    source-dirs: ./benchmark/
    dependencies:
      - brainhask
      - filepath
      - file-embed
      - text
    ghc-options:
      - -O2
      - -funbox-strict-fields
      - -rtsopts
      - -threaded
      - -with-rtsopts=-N
      - -Wall
