---
name: brainhask
version: 0.0.0.0

license: MIT
license-file: LICENSE

dependencies:
  - base
  - parsec
  - either
  - transformers
  - pipes
  - bytestring
  - optparse-applicative
  - directory

library:
  source-dirs: ./src/

executables:
  brainhask:
    main: Main.hs
    source-dirs: ./src/
    ghc-options:
      - -rtsopts
      - -threaded
      - -with-rtsopts=-N
